Edit user device screen
DuyNguyen05/devices_management pull request #29
Opened 2019-09-16 09:59 UTC by DuyNguyen05

- show modal edit 
- having search input with suggestion 
- update user using device

2019-09-18 06:25 UTC, anhtd-307 requested changes

2019-09-18 06:25 UTC, anhtd-307 commented on Gemfile
> +gem "httparty"
lặp gem trong gemfile này cu

2019-09-18 06:25 UTC, anhtd-307 commented on app/helpers/google_helper.rb
> +    url = "https://accounts.google.com/o/oauth2/auth?" +
sửa lại dùng URI query để build url

2019-09-18 06:25 UTC, anhtd-307 commented on app/views/requests/edit.js.erb
> +      debugger;
còn debugger

2019-09-19 01:02 UTC, DuyNguyen05 commented on app/helpers/google_helper.rb
> +    url = "https://accounts.google.com/o/oauth2/auth?" +
cái này em k biết sao nó có trọng pull của e ạ vì cái này là a Mỹ làm ạ

2019-09-19 03:25 UTC, DuyNguyen05 commented
Close pull 29 vì trùng vs code của pull 34

2019-09-19 03:25 UTC, closed without merging